#ifndef DEFS_H
#define DEFS_H

#define TILE_SIZE 128
#define GRID_WIDTH 17
#define GRID_HEIGHT 11

#define SCREEN_WIDTH (TILE_SIZE * GRID_WIDTH + 1)
#define SCREEN_HEIGHT (TILE_SIZE * GRID_HEIGHT + 1)

#define WINDOW_WIDTH (SCREEN_WIDTH + TILE_SIZE) 
#define WINDOW_HEIGHT (SCREEN_HEIGHT + TILE_SIZE)

#define SCREEN_MARGIN (TILE_SIZE / 2)

#endif // DEBUG
